SET SQL_SAFE_UPDATES = 0;
delete from employeeprojects;
delete from projects;
delete from employees;
delete from roles;
SET SQL_SAFE_UPDATES = 1;
insert into roles values ('manager');
insert into roles values ('se');
insert into roles values ('ase');
insert into roles values ('hr');
insert into employees (name, email, phone_number, age, nationalid, rolee) values ('g1', 'gs1@k.com', '010', 23, '123456', 'ase');
insert into employees (name, email, phone_number, age, nationalid, rolee) values ('g2', 'gs2@k.com', '011', 23, '1234561', 'se');
insert into employees (name, email, phone_number, age, nationalid, rolee) values ('g3', 'gs3@k.com', '012', 23, '12345611', 'manager');
insert into employees (name, email, phone_number, age, nationalid, rolee) values ('g4', 'gs4@k.com', '013', 23, '123456111', 'se');
insert into employees (name, email, phone_number, age, nationalid, rolee) values ('g5', 'gs5@k.com', '014', 23, '1234561111', 'ase');
insert into employees (name, email, phone_number, age, nationalid, rolee) values ('g6', 'gs6@k.com', '015', 23, '12345611111', 'hr');
insert into projects (name, start_date, project_manager) values ('electricity', '2020-01-01', 3);
insert into projects (name, start_date, project_manager) values ('alexbank', '2021-01-01', 2);
insert into employeeprojects (employee, project) values (1, 1);
insert into employeeprojects (employee, project) values (1, 2);
insert into employeeprojects (employee, project) values (5, 1);